volumes:
  pg_data:
  static:                    # Новый volume для статики

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static    # Подключаем volume к backend
    depends_on:
      - db

  frontend:
    build: ./frontend/
    env_file: .env
    command: cp -r /app/build/. /frontend_static/   # Копируем статику
    volumes:
      - static:/frontend_static   # Подключаем volume к frontend

  gateway:
    build: ./gateway/
    env_file: .env
    volumes:
      - static:/staticfiles       # Подключаем volume к nginx
    ports:
      - 8000:80
